// <auto-generated />
using System;
using ClinicaMaisSaude.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicaMaisSaude.Infrastructure.Migrations
{
    [DbContext(typeof(ClinicaDbContext))]
    [Migration("20260815151904_Fase6_PenalidadeIA")]
    partial class Fase6_PenalidadeIA
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.Agendamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AgendamentoOrigemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataHoraConsulta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtCriado")
                        .HasColumnType("datetime2")
                        .HasColumnName("Dt_Criado");

                    b.Property<int?>("EspecialidadeId")
                        .HasColumnType("int");

                    b.Property<bool>("ExigeResultadoPosterior")
                        .HasColumnType("bit");

                    b.Property<bool>("LembreteDuasHorasEnviado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("LembreteManhaEnviado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("NotificacaoPendenteGerada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("ProbabilidadeFalta")
                        .HasColumnType("float");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ResultadoDisponivel")
                        .HasColumnType("bit");

                    b.Property<bool>("ResultadoRetirado")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TipoConsulta")
                        .HasColumnType("int");

                    b.Property<int>("TipoProfissional")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgendamentoOrigemId");

                    b.HasIndex("EspecialidadeId");

                    b.HasIndex("TipoConsulta");

                    b.HasIndex("TipoProfissional");

                    b.HasIndex("PacienteId", "DataHoraConsulta");

                    b.HasIndex("ProfissionalId", "DataHoraConsulta");

                    b.HasIndex("Status", "DataHoraConsulta");

                    b.ToTable("Agendamentos");
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.AgendamentoHistorico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgendamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataAnterior")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataNova")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Dt_Criado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RealizadoPor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("StatusAnterior")
                        .HasColumnType("int");

                    b.Property<int?>("StatusNovo")
                        .HasColumnType("int");

                    b.Property<int>("TipoEvento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgendamentoId");

                    b.HasIndex("StatusAnterior");

                    b.HasIndex("StatusNovo");

                    b.HasIndex("TipoEvento");

                    b.ToTable("AgendamentoHistoricos");
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.EspecialidadeLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("DtCriado")
                        .HasColumnType("datetime2")
                        .HasColumnName("Dt_Criado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("EspecialidadeLookup");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "ClinicaGeral"
                        },
                        new
                        {
                            Id = 1,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "MedicinaDeFamilia"
                        },
                        new
                        {
                            Id = 2,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Pediatria"
                        },
                        new
                        {
                            Id = 3,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "GinecologiaEObstetricia"
                        },
                        new
                        {
                            Id = 4,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Cardiologia"
                        },
                        new
                        {
                            Id = 5,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Dermatologia"
                        },
                        new
                        {
                            Id = 6,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Endocrinologia"
                        },
                        new
                        {
                            Id = 7,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Gastroenterologia"
                        },
                        new
                        {
                            Id = 8,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Neurologia"
                        },
                        new
                        {
                            Id = 9,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "OrtopediaETraumatologia"
                        },
                        new
                        {
                            Id = 10,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Psiquiatria"
                        },
                        new
                        {
                            Id = 11,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Otorrinolaringologia"
                        },
                        new
                        {
                            Id = 12,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Oftalmologia"
                        },
                        new
                        {
                            Id = 13,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Urologia"
                        },
                        new
                        {
                            Id = 14,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Pneumologia"
                        },
                        new
                        {
                            Id = 15,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Reumatologia"
                        },
                        new
                        {
                            Id = 16,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Geriatria"
                        },
                        new
                        {
                            Id = 17,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "MedicinaEsportiva"
                        });
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.Notificacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AgendamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DtCriado")
                        .HasColumnType("datetime2")
                        .HasColumnName("Dt_Criado");

                    b.Property<bool>("Lida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Link")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AgendamentoId");

                    b.HasIndex("UsuarioId", "DtCriado");

                    b.ToTable("Notificacoes", (string)null);
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DtCriado")
                        .HasColumnType("datetime2")
                        .HasColumnName("Dt_Criado");

                    b.Property<int>("SituacaoCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<bool>("TemProblemaMemoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SituacaoCliente");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.Profissional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Crm")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("DtCriado")
                        .HasColumnType("datetime2")
                        .HasColumnName("Dt_Criado");

                    b.Property<int>("TipoProfissional")
                        .HasColumnType("int");

                    b.Property<string>("UfCrm")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TipoProfissional");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Profissionais");
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.ProfissionalEspecialidade", b =>
                {
                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EspecialidadeId")
                        .HasColumnType("int");

                    b.HasKey("ProfissionalId", "EspecialidadeId");

                    b.HasIndex("EspecialidadeId");

                    b.ToTable("ProfissionalEspecialidades");
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.SituacaoClienteLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("DtCriado")
                        .HasColumnType("datetime2")
                        .HasColumnName("Dt_Criado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SituacaoClienteLookup");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Ativo"
                        },
                        new
                        {
                            Id = 2,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Desativado"
                        },
                        new
                        {
                            Id = 3,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Excluido"
                        },
                        new
                        {
                            Id = 4,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Banido"
                        });
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.StatusAgendamentoLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("DtCriado")
                        .HasColumnType("datetime2")
                        .HasColumnName("Dt_Criado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("StatusAgendamentoLookup");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Agendado"
                        },
                        new
                        {
                            Id = 1,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "EmAtendimento"
                        },
                        new
                        {
                            Id = 2,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "AguardandoRetorno"
                        },
                        new
                        {
                            Id = 3,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "RetornoAgendado"
                        },
                        new
                        {
                            Id = 4,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Finalizado"
                        },
                        new
                        {
                            Id = 5,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Faltou"
                        },
                        new
                        {
                            Id = 6,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Cancelado"
                        });
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.TipoConsultaLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("DtCriado")
                        .HasColumnType("datetime2")
                        .HasColumnName("Dt_Criado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TipoConsultaLookup");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Triagem"
                        },
                        new
                        {
                            Id = 1,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Exame"
                        },
                        new
                        {
                            Id = 2,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Vacina"
                        },
                        new
                        {
                            Id = 3,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "ConsultaMedica"
                        },
                        new
                        {
                            Id = 4,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Retorno"
                        });
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.TipoEventoHistoricoLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("DtCriado")
                        .HasColumnType("datetime2")
                        .HasColumnName("Dt_Criado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TipoEventoHistoricoLookup");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Criacao"
                        },
                        new
                        {
                            Id = 2,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "MudancaStatus"
                        },
                        new
                        {
                            Id = 3,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Remarcacao"
                        },
                        new
                        {
                            Id = 4,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Cancelamento"
                        });
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.TipoProfissionalLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("DtCriado")
                        .HasColumnType("datetime2")
                        .HasColumnName("Dt_Criado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TipoProfissionalLookup");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Enfermeira"
                        },
                        new
                        {
                            Id = 1,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Medico"
                        });
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.TipoUsuarioLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("DtCriado")
                        .HasColumnType("datetime2")
                        .HasColumnName("Dt_Criado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TipoUsuarioLookup");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Paciente"
                        },
                        new
                        {
                            Id = 2,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Profissional"
                        },
                        new
                        {
                            Id = 3,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Admin"
                        });
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.TipoViolacaoLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("DtCriado")
                        .HasColumnType("datetime2")
                        .HasColumnName("Dt_Criado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TipoViolacaoLookup");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Injecao"
                        },
                        new
                        {
                            Id = 2,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "UsoIndevido"
                        });
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.UsoInadequadoIA", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DtCriado")
                        .HasColumnType("datetime2")
                        .HasColumnName("Dt_Criado");

                    b.Property<string>("TextoInserido")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TipoViolacao")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TipoViolacao");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsoInadequadoIA", (string)null);
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("BloqueadoAte")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BloqueadoIAAte")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime>("DtCriado")
                        .HasColumnType("datetime2")
                        .HasColumnName("Dt_Criado");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("varchar(11)");

                    b.Property<int>("TentativasLogin")
                        .HasColumnType("int");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimoAcesso")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TipoUsuario");

                    b.ToTable("LoginPortal", (string)null);
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.UsuarioFoto", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FotoBase64")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.ToTable("UsuarioFotos", (string)null);
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.Agendamento", b =>
                {
                    b.HasOne("ClinicaMaisSaude.Domain.Entities.Agendamento", null)
                        .WithMany()
                        .HasForeignKey("AgendamentoOrigemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClinicaMaisSaude.Domain.Entities.EspecialidadeLookup", null)
                        .WithMany()
                        .HasForeignKey("EspecialidadeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClinicaMaisSaude.Domain.Entities.Paciente", "Paciente")
                        .WithMany("Agendamentos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicaMaisSaude.Domain.Entities.Profissional", null)
                        .WithMany()
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicaMaisSaude.Domain.Entities.StatusAgendamentoLookup", null)
                        .WithMany()
                        .HasForeignKey("Status")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicaMaisSaude.Domain.Entities.TipoConsultaLookup", null)
                        .WithMany()
                        .HasForeignKey("TipoConsulta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicaMaisSaude.Domain.Entities.TipoProfissionalLookup", null)
                        .WithMany()
                        .HasForeignKey("TipoProfissional")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.AgendamentoHistorico", b =>
                {
                    b.HasOne("ClinicaMaisSaude.Domain.Entities.Agendamento", "Agendamento")
                        .WithMany()
                        .HasForeignKey("AgendamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicaMaisSaude.Domain.Entities.StatusAgendamentoLookup", null)
                        .WithMany()
                        .HasForeignKey("StatusAnterior")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClinicaMaisSaude.Domain.Entities.StatusAgendamentoLookup", null)
                        .WithMany()
                        .HasForeignKey("StatusNovo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClinicaMaisSaude.Domain.Entities.TipoEventoHistoricoLookup", null)
                        .WithMany()
                        .HasForeignKey("TipoEvento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agendamento");
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.Notificacao", b =>
                {
                    b.HasOne("ClinicaMaisSaude.Domain.Entities.Agendamento", null)
                        .WithMany()
                        .HasForeignKey("AgendamentoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ClinicaMaisSaude.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.Paciente", b =>
                {
                    b.HasOne("ClinicaMaisSaude.Domain.Entities.SituacaoClienteLookup", null)
                        .WithMany()
                        .HasForeignKey("SituacaoCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicaMaisSaude.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.Profissional", b =>
                {
                    b.HasOne("ClinicaMaisSaude.Domain.Entities.TipoProfissionalLookup", null)
                        .WithMany()
                        .HasForeignKey("TipoProfissional")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicaMaisSaude.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.ProfissionalEspecialidade", b =>
                {
                    b.HasOne("ClinicaMaisSaude.Domain.Entities.EspecialidadeLookup", null)
                        .WithMany()
                        .HasForeignKey("EspecialidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicaMaisSaude.Domain.Entities.Profissional", "Profissional")
                        .WithMany("Especialidades")
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("ClinicaMaisSaude.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.UsoInadequadoIA", b =>
                {
                    b.HasOne("ClinicaMaisSaude.Domain.Entities.TipoViolacaoLookup", null)
                        .WithMany()
                        .HasForeignKey("TipoViolacao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicaMaisSaude.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Violacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("ClinicaMaisSaude.Domain.Entities.TipoUsuarioLookup", null)
                        .WithMany()
                        .HasForeignKey("TipoUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.UsuarioFoto", b =>
                {
                    b.HasOne("ClinicaMaisSaude.Domain.Entities.Usuario", null)
                        .WithOne("Foto")
                        .HasForeignKey("ClinicaMaisSaude.Domain.Entities.UsuarioFoto", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.Paciente", b =>
                {
                    b.Navigation("Agendamentos");
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.Profissional", b =>
                {
                    b.Navigation("Especialidades");
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Foto");

                    b.Navigation("Violacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
