// <auto-generated />
using System;
using ClinicaMaisSaude.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicaMaisSaude.Infrastructure.Migrations
{
    [DbContext(typeof(ClinicaDbContext))]
    [Migration("20260801214738_RemoverSeedAdminHardcoded")]
    partial class RemoverSeedAdminHardcoded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.Agendamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AgendamentoOrigemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataHoraConsulta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtCriado")
                        .HasColumnType("datetime2")
                        .HasColumnName("Dt_Criado");

                    b.Property<int?>("EspecialidadeId")
                        .HasColumnType("int");

                    b.Property<bool>("ExigeResultadoPosterior")
                        .HasColumnType("bit");

                    b.Property<bool>("LembreteDuasHorasEnviado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("LembreteManhaEnviado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("NotificacaoPendenteGerada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("ProbabilidadeFalta")
                        .HasColumnType("float");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ResultadoDisponivel")
                        .HasColumnType("bit");

                    b.Property<bool>("ResultadoRetirado")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TipoConsulta")
                        .HasColumnType("int");

                    b.Property<int>("TipoProfissional")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId", "DataHoraConsulta");

                    b.HasIndex("ProfissionalId", "DataHoraConsulta");

                    b.HasIndex("Status", "DataHoraConsulta");

                    b.ToTable("Agendamentos");
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.AgendamentoHistorico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgendamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataAnterior")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataNova")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Dt_Criado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RealizadoPor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("StatusAnterior")
                        .HasColumnType("int");

                    b.Property<int?>("StatusNovo")
                        .HasColumnType("int");

                    b.Property<int>("TipoEvento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgendamentoId");

                    b.ToTable("AgendamentoHistoricos");
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.Notificacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AgendamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DtCriado")
                        .HasColumnType("datetime2")
                        .HasColumnName("Dt_Criado");

                    b.Property<bool>("Lida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Link")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AgendamentoId");

                    b.HasIndex("UsuarioId", "DtCriado");

                    b.ToTable("Notificacoes", (string)null);
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("BloqueadoIAAte")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime>("DtCriado")
                        .HasColumnType("datetime2")
                        .HasColumnName("Dt_Criado");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("PenalidadeRemovidaAvisar")
                        .HasColumnType("bit");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<bool>("TemProblemaMemoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Cpf");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.Profissional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Crm")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("DtCriado")
                        .HasColumnType("datetime2")
                        .HasColumnName("Dt_Criado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TipoProfissional")
                        .HasColumnType("int");

                    b.Property<string>("UfCrm")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Profissionais");
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.ProfissionalEspecialidade", b =>
                {
                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EspecialidadeId")
                        .HasColumnType("int");

                    b.HasKey("ProfissionalId", "EspecialidadeId");

                    b.ToTable("ProfissionalEspecialidades");
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.StatusAgendamentoLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("DtCriado")
                        .HasColumnType("datetime2")
                        .HasColumnName("Dt_Criado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("StatusAgendamentoLookup");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Agendado"
                        },
                        new
                        {
                            Id = 1,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "EmAtendimento"
                        },
                        new
                        {
                            Id = 2,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "AguardandoRetorno"
                        },
                        new
                        {
                            Id = 3,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "RetornoAgendado"
                        },
                        new
                        {
                            Id = 4,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Finalizado"
                        },
                        new
                        {
                            Id = 5,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Faltou"
                        },
                        new
                        {
                            Id = 6,
                            DtCriado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Cancelado"
                        });
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.UsoInadequadoIA", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DtCriado")
                        .HasColumnType("datetime2")
                        .HasColumnName("Dt_Criado");

                    b.Property<string>("TextoInserido")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TipoViolacao")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsoInadequadoIA", (string)null);
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("BloqueadoAte")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("DtCriado")
                        .HasColumnType("datetime2")
                        .HasColumnName("Dt_Criado");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FotoBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TentativasLogin")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimoAcesso")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("LoginPortal", (string)null);
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.Agendamento", b =>
                {
                    b.HasOne("ClinicaMaisSaude.Domain.Entities.Paciente", "Paciente")
                        .WithMany("Agendamentos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.AgendamentoHistorico", b =>
                {
                    b.HasOne("ClinicaMaisSaude.Domain.Entities.Agendamento", "Agendamento")
                        .WithMany()
                        .HasForeignKey("AgendamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agendamento");
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.Notificacao", b =>
                {
                    b.HasOne("ClinicaMaisSaude.Domain.Entities.Agendamento", null)
                        .WithMany()
                        .HasForeignKey("AgendamentoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ClinicaMaisSaude.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.Paciente", b =>
                {
                    b.HasOne("ClinicaMaisSaude.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.Profissional", b =>
                {
                    b.HasOne("ClinicaMaisSaude.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.ProfissionalEspecialidade", b =>
                {
                    b.HasOne("ClinicaMaisSaude.Domain.Entities.Profissional", "Profissional")
                        .WithMany("Especialidades")
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("ClinicaMaisSaude.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.UsoInadequadoIA", b =>
                {
                    b.HasOne("ClinicaMaisSaude.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Violacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.Paciente", b =>
                {
                    b.Navigation("Agendamentos");
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.Profissional", b =>
                {
                    b.Navigation("Especialidades");
                });

            modelBuilder.Entity("ClinicaMaisSaude.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Violacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
